### ISSUE TITLE
Authorization URI blocking error

### ISSUE THREAD

**Issue by Yaroslaw9050** [hippogamesunity/SimpleFacebookSignIn#1]
Hello!

When using Facebook authentication, I encountered a URI blocking error. According to the git guide, I configured the redirection, changed the settings in the FacebookAuthSettings and in the manifest, but I get an error when trying to autolog. Added a translation of the error text below:

"The redirect failed because the destination URI is not listed as an allowed URI in the OAuth Client Settings section of the application. Make sure OAuth login is enabled for the client and web forms, and add all of your application domains as valid OAuth redirect URIs."

Client ID is equal Facebook App ID

![image](https://github.com/hippogamesunity/SimpleFacebookSignIn/assets/67838013/f50eaa4a-f918-475d-a3d8-b61feed051bb)
![image](https://github.com/hippogamesunity/SimpleFacebookSignIn/assets/67838013/ddaaf52b-bcbc-4a72-b43a-84ca050f75ea)
![image](https://github.com/hippogamesunity/SimpleFacebookSignIn/assets/67838013/0557e004-fd2b-4915-93c5-a7f98636cc74)
![image](https://github.com/hippogamesunity/SimpleFacebookSignIn/assets/67838013/ba25d852-651f-4741-9ad2-04912b38268d)

**Comment by hippogamesunity** [comment]
Hello, does the asset work with default settings out of the box?
Here is the screenshot of my app settings
![image](https://github.com/hippogamesunity/SimpleFacebookSignIn/assets/7318172/2cfaf71d-a8b2-46e1-813a-d4c6905c1253)

Please also note that Facebook is blocked in Russia, and you may have to use VPN for auth.

**Comment by hippogamesunity** [comment]
I hope the issue is now solved. Please feel free to check FAQ as well https://github.com/hippogamesunity/SimpleFacebookSignIn/wiki/FAQ-&-Troubleshooting
